__default__:
    partition: 'norm'
    threads: 8
    mem: '16g'
    time: '1-00:00:00'
    extra: ' --gres=lscratch:20'

cram__check_md5:
    partition: 'norm'
    threads: 8
    mem: '16g'
    time: '1-00:00:00'
    extra: ' --gres=lscratch:20'