cachedir: cache
docker:
    gatk: docker://broadinstitute/gatk:4.5.0.0
    deepvariant: docker://google/deepvariant:1.6.1
    deepvariant-gpu: docker://google/deepvariant:1.6.1-gpu
    canvas: docker://diracrnhlbi.azurecr.io/bio/canvas:1.40.0.1613
    octopus: docker://funsinaime/octopus:0.7.4
    muse: docker://funsinaime/muse:2.1
    delly: docker://funsinaime/delly:1.2.6
    vardict: docker://funsinaime/vardict-java:1.8.3
singularity:
    melt: library://funsinaime/mei/melt:2.2.2
simg:
    samtools: https://depot.galaxyproject.org/singularity/samtools%3A1.19.2--h50ea8bc_1
    mosdepth: https://depot.galaxyproject.org/singularity/mosdepth%3A0.3.7--hd299d5a_0
    strelka: https://depot.galaxyproject.org/singularity/strelka%3A2.9.7--0
    manta: https://depot.galaxyproject.org/singularity/manta%3A1.6.0--h9ee0642_2
    verifybamid2: https://depot.galaxyproject.org/singularity/verifybamid2%3A2.0.1--h81e4b3e_10
    peddy: https://depot.galaxyproject.org/singularity/peddy%3A0.4.8--pyh5e36f6f_0
    tiddit: https://depot.galaxyproject.org/singularity/tiddit%3A3.7.0--py312h1f1cfbb_0
    hla-la: https://depot.galaxyproject.org/singularity/hla-la%3A1.0.3--hdcf5f25_2
    gridss: https://depot.galaxyproject.org/singularity/gridss%3A2.13.2--h50ea8bc_3
    msisensor-pro: https://depot.galaxyproject.org/singularity/msisensor-pro%3A1.2.0--hfc31af2_0
    gripss: https://depot.galaxyproject.org/singularity/hmftools-gripss%3A2.4--hdfd78af_0
    bcftools: https://depot.galaxyproject.org/singularity/bcftools%3A1.9--ha228f0b_4
    cnvkit: https://depot.galaxyproject.org/singularity/cnvkit%3A0.9.9--pyhdfd78af_0
    amber: https://depot.galaxyproject.org/singularity/hmftools-amber%3A4.0.1--hdfd78af_0
    cobalt: https://depot.galaxyproject.org/singularity/hmftools-cobalt%3A1.16--hdfd78af_0
    purple: https://depot.galaxyproject.org/singularity/hmftools-purple%3A4.0.2--hdfd78af_0
    annotsv: https://depot.galaxyproject.org/singularity/annotsv%3A3.4.2--py312hdfd78af_0